# css.yaml -
#
# This dataset specifies configuration values that are substituted into
# stylesheet templates.  Ideally, it should be possible to change
# overall look and feel information that permeates many stylesheets, such
# as colors and fonts, simply by making changes here.

# Overall background color:
background:        #FFFFFF

# Overall foreground color:
color:             #000000

# Colors to use in "reverse video" situations, with light text on a
# dark background:
reverseBackground: #687291
reverseColor:      #FFFFFF

# A series of compatible background colors, in order from lightest to
# darkest (used for odd-even table shadings, etc.):
background1:       #EEEFF2
background2:       #DFE1E7
background3:       #C9D0DC
background4:       #B0BCC8

# Color to use for displaying error messages that need to stand out:
errorColor:        #DD0000

# Overall font information.  Note: specifying font sizes as percentages
# rather than absolute size enables features such as control-plus and
# control-minus in Firefox.
fontFamily:       "Tahoma, Arial, sans-serif"
fontSize:         80%

# Padding around table entries and similar things where text is
# enclosed in a region:
sidePadding:      10px
topBotPadding:    2px

# IE and Firefox have different default margins around the entire page
# body; this constant makes IE like Firefox.
pageMargin:       8px