# dataManagers.yaml --
#
# This dataset defines the "built-in" data managers for Fiz.  These
# data managers are used primarily for demonstration purposes.

raw:
  class:         RawDataManager

# Used by demos to read datasets from disk files.
demo:
  class:         FileDataManager
  pathTemplate:  @home/WEB-INF/demo