package org.fiz;

import java.sql.*;
import java.util.*;
import org.apache.log4j.*;

import org.fiz.test.*;

/**
 * Junit tests for the SqlDataManager class.
 */

public class SqlDataManagerTest extends junit.framework.TestCase {
    // The following class is used to create dummy requests.
    protected static class NullRequest extends SqlDataManager.SqlRequest {
        // The following variable allows a test to control how long the
        // request takes to execute.
        protected boolean hangAround = false;
        protected boolean finished = false;
        public void run() {
            while (hangAround) {
                try {
                    Thread.sleep(1);
                }
                catch (InterruptedException e) {
                    // Ignore this exception.
                }
            }
            finished = true;
        }
    }

    // The following class is used to spawn a separate thread to wait
    // for all pending requests to complete.

    protected static class Waiter implements Runnable {
        boolean finished = false;
        boolean sleeping = false;
        SqlDataManager manager;
        public Waiter(SqlDataManager manager) {
            this.manager = manager;
        }
        public void run() {
            sleeping = true;
            manager.waitForCompletion();
            finished = true;
        }
    }

    protected static SqlDataManager manager = null;
    // The following variable holds any log entries generated by the test.
    protected static StringBuilder log;

    public void setUp() {
        // Only initialize the database once, then use that setup for
        // all of the tests.  As of 4/2009 this reduced the running time
        // for this file from 16 seconds to less than 3 seconds.
        if (manager == null) {
            StringAppender appender = new StringAppender();
            SqlDataManager.logger = Logger.getRootLogger();
            SqlDataManager.logger.removeAllAppenders();
            SqlDataManager.logger.addAppender(appender);
            log = appender.log;
            Config.init("test/testData/WEB-INF/config");
            manager = new SqlDataManager(new Dataset(
                    "driverClass", "com.mysql.jdbc.Driver",
                    "serverUrl", "jdbc:mysql://localhost:3306/test",
                    "user", "test",
                    "password", "test"));

            // Initialize the "people" table; individual tests should
            // not modify the contents of this table.
            try {
                manager.updateWithSql("DROP table people;");
            }
            catch (SqlError e) {
                // Ignore error; this probably just means that the table
                // doesn't already exist.
            }
            manager.updateWithSql("CREATE TABLE people " +
                    "(id INT AUTO_INCREMENT, PRIMARY KEY(id)," +
                    "first VARCHAR(20)," +
                    "last VARCHAR(20)," +
                    "state VARCHAR(32)," +
                    "age INT," +
                    "weight INT);");
            try {
                manager.updateWithSql("DROP table states;");
            }
            catch (SqlError e) {
                // Ignore error; this probably just means that the table
                // doesn't already exist.
            }
            manager.updateWithSql("CREATE TABLE states " +
                    "(id INT AUTO_INCREMENT, PRIMARY KEY(id), " +
                    "name VARCHAR(32)," +
                    "capital VARCHAR(32)," +
                    "timezone VARCHAR(32));");
            manager.collectMetadata();
            Dataset in = YamlDataset.newStringInstance(
                    "record:\n" +
                    "  - first:  Alice\n" +
                    "    last:   Adams\n" +
                    "    state:  California\n" +
                    "    age:    24\n" +
                    "    weight: 115\n" +
                    "  - first:  Bob\n" +
                    "    last:   Brennan\n" +
                    "    state:  New York\n" +
                    "    age:    18\n" +
                    "    weight: 190\n" +
                    "  - first:  Carol\n" +
                    "    last:   Collins\n" +
                    "    state:  California\n" +
                    "    age:    32\n" +
                    "    weight: 130\n");
            for (Dataset row : in.getChildren("record")) {
                manager.insert("people", row);
            }
        } else {
            // Make sure there are no requests from earlier tests still
            // running, and perform various other resets.
            manager.waitForCompletion();
            log.setLength(0);
        }
    }

    // Utility method to close the current database connection.
    protected void closeConnection() {
        try {
            manager.connection.close();
            manager.reopens = 0;
        }
        catch (SQLException e) {
            // Ignore exceptions.
        }
    }

    public void test_sanityCheck_synchronous() {
        Dataset out = manager.findWithSql("SELECT * FROM people;");
        assertEquals("retrieved rows",
                "record:\n" +
                "  - age:    24\n" +
                "    first:  Alice\n" +
                "    id:     1\n" +
                "    last:   Adams\n" +
                "    state:  California\n" +
                "    weight: 115\n" +
                "  - age:    18\n" +
                "    first:  Bob\n" +
                "    id:     2\n" +
                "    last:   Brennan\n" +
                "    state:  New York\n" +
                "    weight: 190\n" +
                "  - age:    32\n" +
                "    first:  Carol\n" +
                "    id:     3\n" +
                "    last:   Collins\n" +
                "    state:  California\n" +
                "    weight: 130\n", out.toString());
    }
    public void test_sanityCheck_asynchronous() {
        DataRequest request = manager.newFindRequest("people", "State",
                "California");
        assertEquals("retrieved rows",
                "record:\n" +
                "  - age:    24\n" +
                "    first:  Alice\n" +
                "    id:     1\n" +
                "    last:   Adams\n" +
                "    state:  California\n" +
                "    weight: 115\n" +
                "  - age:    32\n" +
                "    first:  Carol\n" +
                "    id:     3\n" +
                "    last:   Collins\n" +
                "    state:  California\n" +
                "    weight: 130\n", request.getResponseOrAbort().toString());
    }

    public void test_RequestRunner_multipleRequests() {
        SqlDataManager.SqlRequest request1 = new SqlDataManager.FindRequest(
                "people", "age", "24");
        SqlDataManager.SqlRequest request2 = new SqlDataManager.FindRequest(
                "people", "age", "18");
        manager.firstRequest = request1;
        request1.next = request2;
        manager.lastRequest = request2;
        request1.manager = request2.manager = manager;
        SqlDataManager.RequestRunner runner = new SqlDataManager.RequestRunner(
                manager);
        runner.run();
        assertEquals("first request finished", true, request1.isComplete());
        assertEquals("second request finished", true, request2.isComplete());
        assertEquals("result of first request",
                "record:\n" +
                "    age:    24\n" +
                "    first:  Alice\n" +
                "    id:     1\n" +
                "    last:   Adams\n" +
                "    state:  California\n" +
                "    weight: 115\n", request1.getResponseOrAbort().toString());
        assertEquals("result of second request",
                "record:\n" +
                "    age:    18\n" +
                "    first:  Bob\n" +
                "    id:     2\n" +
                "    last:   Brennan\n" +
                "    state:  New York\n" +
                "    weight: 190\n", request2.getResponseOrAbort().toString());
    }
    public void test_RequestRunner_SqlError() {
        SqlDataManager.SqlRequest request = new SqlDataManager.FindRequest(
                "bogusTable", "age", "24");
        manager.firstRequest = request;
        request.manager = manager;
        SqlDataManager.RequestRunner runner = new SqlDataManager.RequestRunner(
                manager);
        runner.run();
        assertEquals("first request finished", true, request.isComplete());
        assertEquals("error information", "SQL error in SqlDataManager.find: " +
                "table 'test.bogustable' doesn't exist",
                request.getDetailedErrorMessage());
    }
    public void test_RequestRunner_otherError() {
        SqlDataManager.SqlRequest request = new SqlDataManager.SqlRequest() {
            public void run() {
                setName("test");
                throw new InternalError("sample error message");
            }
        };
        manager.firstRequest = request;
        request.manager = manager;
        SqlDataManager.RequestRunner runner = new SqlDataManager.RequestRunner(
                manager);
        runner.run();
        assertEquals("first request finished", true, request.isComplete());
        assertEquals("error information",
                "InternalError exception in test data request: " +
                "sample error message",
                request.getDetailedErrorMessage());
    }
    public void test_RequestRunner_otherErrorNoName() {
        SqlDataManager.SqlRequest request = new SqlDataManager.SqlRequest() {
            public void run() {
                throw new InternalError("sample error message");
            }
        };
        manager.firstRequest = request;
        request.manager = manager;
        SqlDataManager.RequestRunner runner = new SqlDataManager.RequestRunner(
                manager);
        runner.run();
        assertEquals("first request finished", true, request.isComplete());
        assertEquals("error information",
                "InternalError exception in unknown SqlDataManager data " +
                "request: sample error message",
                request.getDetailedErrorMessage());
    }

    public void test_constructor_badDriverClass() throws SQLException {
        boolean gotException = false;
        try {
            new SqlDataManager(new Dataset("serverUrl", "urlabc",
                    "user", "test", "password", "test",
                    "driverClass", "com.bogus.missing"));
        }
        catch (InternalError e) {
            assertEquals("exception message",
                    "SqlDataManager couldn't load driver class " +
                    "\"com.bogus.missing\"", e.getMessage());
            gotException = true;
        }
        assertEquals("exception happened", true, gotException);
    }
    public void test_constructor_cantConnectToServer() throws SQLException {
        boolean gotException = false;
        try {
            new SqlDataManager(new Dataset("driverClass",
                    "com.mysql.jdbc.Driver", "serverUrl",
                    "jdbc:mysql://localhost:3307/bogus",
                    "user", "u1", "password", "p1"));
        }
        catch (InternalError e) {
            TestUtil.assertSubstring("first part of exception message",
                    "SqlDataManager couldn't create connection with server " +
                    "at \"jdbc:mysql://localhost:3307/bogus\":",
                    e.getMessage());
            gotException = true;
        }
        assertEquals("exception happened", true, gotException);
    }

    public void test_clearTable() {
        manager.insert("states", new Dataset("name", "Virginia"));
        manager.clearTable("states");
        Dataset out = manager.findWithSql("SELECT * FROM states;");
        assertEquals("retrieved rows", "", out.toString());
    }
    public void test_clearTable_fatalError() {
        boolean gotException = false;
        try {
            manager.clearTable("bogus");
        }
        catch (SqlError e) {
            assertEquals("exception message",
                    "SQL error in SqlDataManager.clearTable: table " +
                    "'test.bogus' doesn't exist",
                    e.getMessage());
            gotException = true;
        }
        assertEquals("exception happened", true, gotException);
    }
    public void test_clearTable_retriableError() {
        manager.insert("states", new Dataset("name", "Virginia"));
        closeConnection();
        manager.clearTable("states");
        Dataset out = manager.findWithSql("SELECT * FROM states;");
        assertEquals("retrieved rows", "", out.toString());
        assertEquals("count of reopens", 1, manager.reopens);
    }
    public void test_newClearTableRequest() {
        manager.insert("states", new Dataset("name", "Virginia"));
        DataRequest request = manager.newClearTableRequest("states");
        assertEquals("empty request response", "",
                request.getResponseData().toString());
        Dataset out = manager.findWithSql("SELECT * FROM states;");
        assertEquals("retrieved rows", "", out.toString());
    }

    public void test_delete() {
        manager.clearTable("states");
        manager.insert("states", new Dataset("name", "California",
                "capital", "Sacramento", "id", "442"));
        manager.insert("states", new Dataset("name", "California",
                "capital", "Palo Alto", "id", "443"));
        manager.insert("states", new Dataset("name", "Colorado",
                "capital", "Denver", "id", "999"));
        manager.delete("states", "name", "California");
        Dataset out = manager.findWithSql("SELECT name, capital FROM states;");
        assertEquals("table after deletion",
                "record:\n" +
                "    capital: Denver\n" +
                "    name:    Colorado\n", out.toString());
    }
    public void test_delete_fatalError() {
        boolean gotException = false;
        try {
            manager.delete("bogus", "first", "Alice");
        }
        catch (SqlError e) {
            assertEquals("exception message", "SQL error in " +
                    "SqlDataManager.delete: table 'test.bogus' doesn't exist",
                    e.getMessage());
            gotException = true;
        }
        assertEquals("exception happened", true, gotException);
    }
    public void test_delete_retriableError() {
        manager.clearTable("states");
        manager.insert("states", new Dataset("name", "California",
                "capital", "Sacramento", "id", "442"));
        manager.insert("states", new Dataset("name", "California",
                "capital", "Palo Alto", "id", "443"));
        manager.insert("states", new Dataset("name", "Colorado",
                "capital", "Denver", "id", "999"));
        closeConnection();
        manager.delete("states", "name", "California");
        Dataset out = manager.findWithSql("SELECT name, capital FROM states;");
        assertEquals("table after deletion",
                "record:\n" +
                "    capital: Denver\n" +
                "    name:    Colorado\n", out.toString());
        assertEquals("count of reopens", 1, manager.reopens);
    }
    public void test_newDeleteRequest() {
        manager.clearTable("states");
        manager.insert("states", new Dataset("name", "California",
                "capital", "Sacramento", "id", "442"));
        manager.insert("states", new Dataset("name", "California",
                "capital", "Palo Alto", "id", "443"));
        manager.insert("states", new Dataset("name", "Colorado",
                "capital", "Denver", "id", "999"));
        DataRequest request = manager.newDeleteRequest("states",
                "name", "California");
        assertEquals("empty request response", "",
                request.getResponseData().toString());
        Dataset out = manager.findWithSql("SELECT name, capital FROM states;");
        assertEquals("table after deletion",
                "record:\n" +
                "    capital: Denver\n" +
                "    name:    Colorado\n", out.toString());
    }

    public void test_find() {
        Dataset out = manager.find("people", "state", "California");
        assertEquals("retrieved rows", "record:\n" +
                "  - age:    24\n" +
                "    first:  Alice\n" +
                "    id:     1\n" +
                "    last:   Adams\n" +
                "    state:  California\n" +
                "    weight: 115\n" +
                "  - age:    32\n" +
                "    first:  Carol\n" +
                "    id:     3\n" +
                "    last:   Collins\n" +
                "    state:  California\n" +
                "    weight: 130\n", out.toString());
    }
    public void test_find_fatalError() {
        boolean gotException = false;
        try {
            Dataset out = manager.find("bogus", "first", "Alice");
        }
        catch (SqlError e) {
            assertEquals("exception message",
                    "SQL error in SqlDataManager.find: table " +
                    "'test.bogus' doesn't exist",
                    e.getMessage());
            gotException = true;
        }
        assertEquals("exception happened", true, gotException);
    }
    public void test_find_retriableError() {
        closeConnection();
        Dataset out = manager.find("people", "first", "Alice");
        assertEquals("retrieved rows", "record:\n" +
                "    age:    24\n" +
                "    first:  Alice\n" +
                "    id:     1\n" +
                "    last:   Adams\n" +
                "    state:  California\n" +
                "    weight: 115\n", out.toString());
        assertEquals("count of reopens", 1, manager.reopens);
    }
    public void test_newFindRequest() {
        DataRequest request = manager.newFindRequest("people", "first",
                "Carol");
        assertEquals("retrieved rows", "record:\n" +
                "    age:    32\n" +
                "    first:  Carol\n" +
                "    id:     3\n" +
                "    last:   Collins\n" +
                "    state:  California\n" +
                "    weight: 130\n", request.getResponseOrAbort().toString());
    }

    public void test_findWithSql() {
        Dataset out = manager.findWithSql("SELECT first, last FROM people " +
                "WHERE state = 'California';");
        assertEquals("retrieved rows", "record:\n" +
                "  - first: Alice\n" +
                "    last:  Adams\n" +
                "  - first: Carol\n" +
                "    last:  Collins\n", out.toString());
    }
    public void test_findWithSql_fatalError() {
        boolean gotException = false;
        try {
            manager.findWithSql("SELECT * FROM bogusTable;");
        }
        catch (SqlError e) {
            assertEquals("exception message",
                    "SQL error in SqlDataManager.findWithSql: " +
                    "table 'test.bogustable' doesn't exist",
                    e.getMessage());
            gotException = true;
        }
        assertEquals("exception happened", true, gotException);
    }
    public void test_findWithSql_retriableError() {
        closeConnection();
        Dataset out = manager.findWithSql("SELECT first, last FROM people " +
                "WHERE state = 'California';");
        assertEquals("retrieved rows", "record:\n" +
                "  - first: Alice\n" +
                "    last:  Adams\n" +
                "  - first: Carol\n" +
                "    last:  Collins\n", out.toString());
        assertEquals("count of reopens", 1, manager.reopens);
    }
    public void test_newFindWithSqlRequest() {
        DataRequest request = manager.newFindWithSqlRequest(
                "SELECT first, last FROM people WHERE state = 'California';");
        assertEquals("retrieved rows", "record:\n" +
                "  - first: Alice\n" +
                "    last:  Adams\n" +
                "  - first: Carol\n" +
                "    last:  Collins\n",
                request.getResponseOrAbort().toString());
    }

    public void test_findWithSql_withTemplate() {
        Dataset out = manager.findWithSql("SELECT first, last FROM people " +
                "WHERE state = @state AND first = @first;",
                new Dataset("table", "people", "state", "California",
                "first", "Alice"));
        assertEquals("retrieved rows", "record:\n" +
                "    first: Alice\n" +
                "    last:  Adams\n", out.toString());
    }
    public void test_findWithSql_withTemplate_fatalError() {
        boolean gotException = false;
        try {
            manager.findWithSql("SELECT @what FROM bogusTable;",
                    new Dataset("what", "*"));
        }
        catch (SqlError e) {
            assertEquals("exception message",
                    "SQL error in SqlDataManager.findWithSql: " +
                    "table 'test.bogustable' doesn't exist",
                    e.getMessage());
            gotException = true;
        }
        assertEquals("exception happened", true, gotException);
    }
    public void test_findWithSql_withTemplate_retriableError() {
        closeConnection();
        Dataset out = manager.findWithSql("SELECT first, last FROM people " +
                "WHERE state = @state AND first = @first;",
                new Dataset("table", "people", "state", "California",
                "first", "Alice"));
        assertEquals("retrieved rows", "record:\n" +
                "    first: Alice\n" +
                "    last:  Adams\n", out.toString());
        assertEquals("count of reopens", 1, manager.reopens);
    }
    public void test_newFindWithSqlRequest_withTemplate() {
        DataRequest request = manager.newFindWithSqlRequest(
                "SELECT first, last FROM people " +
                "WHERE state = @state AND first = @first;",
                new Dataset("table", "people", "state", "California",
                "first", "Alice"));
        assertEquals("retrieved rows", "record:\n" +
                "    first: Alice\n" +
                "    last:  Adams\n",
                request.getResponseOrAbort().toString());
    }

    public void test_insert() {
        manager.clearTable("states");
        manager.insert("states", new Dataset("name", "California",
                "capital", "Sacramento", "id", "442",
                "bogus", "ignore this"));
        manager.insert("states", new Dataset("name", "Colorado"));
        Dataset out = manager.findWithSql("SELECT name, capital FROM states;");
        assertEquals("retrieved rows",
                "record:\n" +
                "  - capital: Sacramento\n" +
                "    name:    California\n" +
                "  - capital: \"\"\n" +
                "    name:    Colorado\n", out.toString());
    }
    public void test_insert_fatalError() {
        boolean gotException = false;
        try {
            manager.insert("people", new Dataset("id", "1"));
        }
        catch (SqlError e) {
            assertEquals("exception message",
                    "SQL error in SqlDataManager.insert: " +
                    "duplicate entry '1' for key 1",
                    e.getMessage());
            gotException = true;
        }
        assertEquals("exception happened", true, gotException);
    }
    public void test_insert_retriableError() {
        manager.clearTable("states");
        manager.insert("states", new Dataset("name", "California",
                "capital", "Sacramento", "id", "442",
                "bogus", "ignore this"));
        closeConnection();
        manager.insert("states", new Dataset("name", "Colorado"));
        Dataset out = manager.findWithSql("SELECT name, capital FROM states;");
        assertEquals("retrieved rows",
                "record:\n" +
                "  - capital: Sacramento\n" +
                "    name:    California\n" +
                "  - capital: \"\"\n" +
                "    name:    Colorado\n", out.toString());
        assertEquals("count of reopens", 1, manager.reopens);
    }
    public void test_newInsertRequest() {
        manager.clearTable("states");
        DataRequest request = manager.newInsertRequest("states",
                new Dataset("name", "California",
                "capital", "Sacramento", "id", "442",
                "bogus", "ignore this"));
        assertEquals("empty request response", "",
                request.getResponseData().toString());
        Dataset out = manager.findWithSql("SELECT name, capital FROM states;");
        assertEquals("retrieved rows",
                "record:\n" +
                "    capital: Sacramento\n" +
                "    name:    California\n", out.toString());
    }

    public void test_update() {
        manager.clearTable("states");
        manager.updateWithSql(
                "INSERT INTO states (name, capital) " +
                "VALUES ('Virginia', 'Richmond');",
                "INSERT INTO states (name, capital) " +
                "VALUES ('California', 'Sacramento');");
        manager.update ("states", "capital", "Sacramento", new Dataset(
                "capital", "Berkeley", "bogus1", "99"));
        Dataset out = manager.findWithSql("SELECT name, capital " +
                "FROM states WHERE name = 'California';");
        assertEquals("modified row", "record:\n" +
                "    capital: Berkeley\n" +
                "    name:    California\n", out.toString());
    }
    public void test_update_fatalError() {
        boolean gotException = false;
        try {
            manager.update ("people", "bogus", "bogus", new Dataset(
                    "state", "Mississippi"));
        }
        catch (SqlError e) {
            assertEquals("error message",
                    "SQL error in SqlDataManager.update: " +
                    "unknown column 'bogus' in 'where clause'",
                    e.getMessage());
            gotException = true;
        }
        assertEquals("exception happened", true, gotException);
    }
    public void test_update_retriableError() {
        manager.clearTable("states");
        manager.updateWithSql(
                "INSERT INTO states (name, capital) " +
                "VALUES ('Virginia', 'Richmond');",
                "INSERT INTO states (name, capital) " +
                "VALUES ('California', 'Sacramento');");
        closeConnection();
        manager.update ("states", "capital", "Sacramento", new Dataset(
                "capital", "Berkeley", "bogus1", "99"));
        Dataset out = manager.findWithSql("SELECT name, capital " +
                "FROM states WHERE name = 'California';");
        assertEquals("modified rows", "record:\n" +
                "    capital: Berkeley\n" +
                "    name:    California\n", out.toString());
        assertEquals("count of reopens", 1, manager.reopens);
    }
    public void test_newUpdateRequest() {
        manager.clearTable("states");
        manager.updateWithSql(
                "INSERT INTO states (name, capital) " +
                "VALUES ('Virginia', 'Richmond');",
                "INSERT INTO states (name, capital) " +
                "VALUES ('California', 'Sacramento');");
        DataRequest request = manager.newUpdateRequest("states", "capital",
                "Sacramento", new Dataset("capital", "Berkeley",
                "bogus1", "99"));
        assertEquals("empty request response", "",
                request.getResponseData().toString());
        Dataset out = manager.findWithSql("SELECT name, capital " +
                "FROM states WHERE name = 'California';");
        assertEquals("retrieved rows",
                "record:\n" +
                "    capital: Berkeley\n" +
                "    name:    California\n", out.toString());
    }

    public void test_updateWithSql_multipleUpdates() {
        manager.clearTable("states");
        manager.updateWithSql(
                "INSERT INTO states (name, capital) " +
                "VALUES ('Michigan', 'Lansing');",
                "UPDATE states SET name = 'Illinois' WHERE name = 'Michigan';");
        Dataset out = manager.findWithSql("SELECT name, capital FROM states;");
        assertEquals("retrieved row", "record:\n" +
                "    capital: Lansing\n" +
                "    name:    Illinois\n", out.toString());
    }
    public void test_updateWithSql_fatalError() {
        boolean gotException = false;
        try {
            manager.updateWithSql("UPDATE bogusTable;");
        }
        catch (SqlError e) {
            TestUtil.assertSubstring("first part of exception message",
                    "SQL error in SqlDataManager.updateWithSql: you " +
                    "have an error in your SQL syntax",
                    e.getMessage());
            gotException = true;
        }
        assertEquals("exception happened", true, gotException);
    }
    public void test_updateWithSql_multipleUpdates_retriableError() {
        manager.clearTable("states");
        closeConnection();
        manager.updateWithSql(
                "INSERT INTO states (name, capital) " +
                "VALUES ('Michigan', 'Lansing');",
                "UPDATE states SET name = 'Illinois' WHERE name = 'Michigan';");
        Dataset out = manager.findWithSql("SELECT name, capital FROM states;");
        assertEquals("retrieved row", "record:\n" +
                "    capital: Lansing\n" +
                "    name:    Illinois\n", out.toString());
        assertEquals("count of reopens", 1, manager.reopens);
    }
    public void test_newUpdateWithSqlRequest() {
        manager.delete("people", "last", "Williams");
        DataRequest request = manager.newUpdateWithSqlRequest(
                "INSERT INTO people (first, last, state) " +
                "VALUES ('David', 'Williams', 'Oregon');",
                "UPDATE people SET state = 'Utah' WHERE first = 'David';");
        assertEquals("empty request response", "",
                request.getResponseData().toString());
        Dataset out = manager.findWithSql("SELECT first, last, state " +
                "FROM people WHERE first = 'David';");
        assertEquals("retrieved rows",
                "record:\n" +
                "    first: David\n" +
                "    last:  Williams\n" +
                "    state: Utah\n", out.toString());
    }

    public void test_updateWithSql_withTemplate() {
        manager.clearTable("states");
        manager.insert("states", new Dataset("name", "Georgia",
                "capital", "Atlanta"));
        manager.updateWithSql(
                "UPDATE states SET name = @state WHERE capital = @capital;",
                new Dataset("state", "West Virginia", "capital", "Atlanta"));
        Dataset out = manager.findWithSql("SELECT name, capital FROM states;");
        assertEquals("retrieved row", "record:\n" +
                "    capital: Atlanta\n" +
                "    name:    West Virginia\n", out.toString());
    }
    public void test_updateWithSql_withTemplate_fatalError() {
        boolean gotException = false;
        try {
            manager.updateWithSql("UPDATE @table;",
                    new Dataset("table", "bogusTable"));
        }
        catch (SqlError e) {
            TestUtil.assertSubstring("first part of exception message",
                    "SQL error in SqlDataManager.updateWithSql: you " +
                    "have an error in your SQL syntax",
                    e.getMessage());
            gotException = true;
        }
        assertEquals("exception happened", true, gotException);
    }
    public void test_updateWithSql_withTemplate_retriableError() {
        manager.clearTable("states");
        manager.insert("states", new Dataset("name", "Georgia",
                "capital", "Atlanta"));
        closeConnection();
        manager.updateWithSql(
                "UPDATE states SET name = @state WHERE capital = @capital;",
                new Dataset("state", "West Virginia", "capital", "Atlanta"));
        Dataset out = manager.findWithSql("SELECT name, capital FROM states;");
        assertEquals("retrieved row", "record:\n" +
                "    capital: Atlanta\n" +
                "    name:    West Virginia\n", out.toString());
    }
    public void test_newUpdateWithSqlRequest_withTemplate() {
        manager.clearTable("states");
        manager.insert("states", new Dataset("name", "California",
                "capital", "Sacramento", "id", "442", "timezone", "PST",
                "bogus", "ignore this"));
        DataRequest request = manager.newUpdateWithSqlRequest(
                "UPDATE states SET capital = @capital WHERE name = @name;",
                new Dataset("name", "California", "capital", "Berkeley"));
        assertEquals("empty request response", "",
                request.getResponseOrAbort().toString());
        Dataset out = manager.findWithSql("SELECT * FROM states;");
        assertEquals("retrieved rows",
                "record:\n" +
                "    capital:  Berkeley\n" +
                "    id:       442\n" +
                "    name:     California\n" +
                "    timezone: PST\n", out.toString());
    }

    // No tests for waitForCompletion here; it's tested by other code below.

    @SuppressWarnings("unchecked")
    public void test_collectMetadata() {
        manager.collectMetadata();
        SqlDataManager.TableInfo info = manager.tables.get("people");
        assertEquals("info exists for people table", true, info != null);
        ArrayList names = new ArrayList();
        names.addAll(info.columnNames);
        Collections.sort(names);
        assertEquals("column names for people table",
                "age, first, id, last, state, weight",
                StringUtil.join(names, ", "));

        info = manager.tables.get("states");
        assertEquals("info exists for states table", true, info != null);
        names = new ArrayList();
        names.addAll(info.columnNames);
        Collections.sort(names);
        assertEquals("column names for states table",
                "capital, id, name, timezone",
                StringUtil.join(names, ", "));
    }

    public void test_getResults_basics() {
        Dataset out = manager.findWithSql("SELECT first, last, age " +
                "FROM people WHERE state = 'California';");
        assertEquals("retrieved rows", "record:\n" +
                "  - age:   24\n" +
                "    first: Alice\n" +
                "    last:  Adams\n" +
                "  - age:   32\n" +
                "    first: Carol\n" +
                "    last:  Collins\n", out.toString());
    }
    public void test_getResults_duplicatedColumnName() {
        manager.clearTable("states");
        manager.insert("states", new Dataset("name", "California",
                "capital", "Sacramento", "id", "442"));
        Dataset out = manager.findWithSql("SELECT people.id, " +
                "states.id, capital FROM people JOIN states " +
                "WHERE people.state = states.name");
        assertEquals("retrieved rows", "record:\n" +
                "  - capital:   Sacramento\n" +
                "    \"people:id\": 1\n" +
                "    \"states:id\": 442\n" +
                "  - capital:   Sacramento\n" +
                "    \"people:id\": 3\n" +
                "    \"states:id\": 442\n", out.toString());
    }
    public void test_getResults_firstDupHasNoTableName() {
        manager.clearTable("states");
        manager.insert("states", new Dataset("name", "California",
                "capital", "Sacramento", "id", "442"));
        Dataset out = manager.findWithSql(
                "SELECT 'xyzzy' id, id FROM states WHERE name = 'California'");
        assertEquals("retrieved rows", "record:\n" +
                "    id:        xyzzy\n" +
                "    \"states:id\": 442\n", out.toString());
    }
    public void test_getResults_secondDupHasNoTableName() {
        manager.clearTable("states");
        manager.insert("states", new Dataset("name", "California",
                "capital", "Sacramento", "id", "442"));
        Dataset out = manager.findWithSql(
                "SELECT id, 'xyzzy' id FROM states WHERE name = 'California'");
        assertEquals("retrieved rows", "record:\n" +
                "    id:        xyzzy\n" +
                "    \"states:id\": 442\n", out.toString());
    }

    public void test_getValidColumns_nonexistentTable() {
        boolean gotException = false;
        try {
            manager.getValidColumns("bogusTable", new Dataset("a", "1"));
        }
        catch (InternalError e) {
            assertEquals("error message",
                    "no database table named \"bogusTable\"",
                    e.getMessage());
            gotException = true;
        }
        assertEquals("exception happened", true, gotException);
    }
    public void test_getValidColumns_checkColumns() {
        ArrayList<String> names = manager.getValidColumns("people",
                new Dataset("bogus1", "24", "first", "Alice",
                "last", "Brown", "bogus2", "35", "id", "14"));
        Collections.sort(names);
        assertEquals("valid columns", "first, id, last",
                StringUtil.join(names, ", "));
    }

    public void test_handleError_reopenConnection() throws SQLException {
        // Close the connection, then try to reopen it twice: the first
        // time will fail because we changed the user name to something
        // incorrect; the second time it should work.
        closeConnection();
        String oldUser = manager.user;
        manager.user = "bogusUser";
        boolean gotException = false;
        try {
                manager.handleError(new SQLException("fake exception"),
                        "in test");
        }
        catch (InternalError e) {
            assertEquals("error message",
                    "SqlDataManager.handleError couldn't reconnect with " +
                    "server at \"jdbc:mysql://localhost:3306/test\": " +
                    "Access denied for user 'bogusUser'@'localhost' " +
                    "(using password: YES)",
                    e.getMessage());
            gotException = true;
        }
        assertEquals("exception happened", true, gotException);
        assertEquals("connection open", true, manager.connection.isClosed());

        // Reset the user name and try again..
        manager.user = oldUser;
        manager.handleError(new SQLException("fake exception"),
                "in test");
        assertEquals("connection open", false, manager.connection.isClosed());
    }
    public void test_handleError_unrecoverableError() throws SQLException {
        boolean gotException = false;
        try {
                manager.handleError(new SQLException("fake exception"),
                        "in test");
        }
        catch (SqlError e) {
            assertEquals("error message",
                    "SQL error in test: fake exception",
                    e.getMessage());
            gotException = true;
        }
        assertEquals("exception happened", true, gotException);
    }

    public void test_popList() throws InterruptedException {
        NullRequest request1 = new NullRequest();
        NullRequest request2 = new NullRequest();
        request1.next = request2;
        manager.firstRequest = request1;
        manager.lastRequest = request2;
        Waiter waiter = new Waiter(manager);
        new Thread(waiter).start();
        for (int i = 0; (i < 100) & (!waiter.sleeping); i++) {
            Thread.sleep(10);
        }
        assertEquals("waiter sleeping", true, waiter.sleeping);
        assertEquals("first result", request2, manager.popList());
        assertEquals("new firstRequest", request2, manager.firstRequest);
        Thread.sleep(10);
        assertEquals("waiter not finished", false, waiter.finished);
        assertEquals("second result", null, manager.popList());
        assertEquals("final firstRequest", null, manager.firstRequest);
        for (int i = 0; (i < 100) & (!waiter.finished); i++) {
            Thread.sleep(10);
        }
        assertEquals("waiter finished", true, waiter.finished);
    }

    public void test_schedule_listEmpty() throws InterruptedException {
        NullRequest request = new NullRequest();
        request.hangAround = true;
        manager.firstRequest = null;
        manager.schedule(request);
        Thread.sleep(10);

        // Check for proper queue structure.
        assertEquals("firstRequest", request, manager.firstRequest);
        assertEquals("lastRequest", request, manager.lastRequest);
        assertEquals("request not finished", false, request.finished);

        // Make sure the request actually got scheduled.
        request.hangAround = false;
        for (int i = 0; (i < 100) & (!request.finished); i++) {
            Thread.sleep(10);
        }
        assertEquals("request finished", true, request.finished);
    }
    public void test_schedule_listNotEmpty() {
        NullRequest request1 = new NullRequest();
        NullRequest request2 = new NullRequest();
        manager.firstRequest = manager.lastRequest = request1;
        manager.schedule(request2);
        assertEquals("firstRequest", request1, manager.firstRequest);
        assertEquals("lastRequest", request2, manager.lastRequest);
    }
}
