# dataRequests.yaml --
#
# This dataset defines the official "built-in" data requests for Fiz.
# Most of these are used primarily for demonstration purposes.

# The following requests are used by the Demo class.
demo:
    error:
        manager: demo
        request: read
        file:    demo
        dataset: bogus.nonexistent
    formError1:
        manager: demo
        request: error
        file:    demo
        dataset: error1
    formError2:
        manager: demo
        request: error
        file:    demo
        dataset: error2
    formError3:
        manager: demo
        request: error
        file:    demo
        dataset: error3
    getCart:
        manager: demo
        request: read
        file:    demo
        dataset: shoppingCart
    getFormData:
        manager: demo
        request: read
        file:    demo
        dataset: formData
    getFruits:
        manager: demo
        request: read
        file:    demo
        dataset: fruits
    getPeople:
        manager: demo
        request: read
        file:    demo
        dataset: people
    getPerson:
        manager: demo
        request: read
        file:    demo
        dataset: person
    noData:
        manager: demo
        request: read
        file:    demo
        dataset: empty
    treeTopLevel:
        manager: demo
        request: read
        file:    demo
        dataset: treeTopLevel