# dataRequests.yaml --
#
# This dataset defines the official "built-in" data requests for Fiz.
# Most of these are used primarily for demonstration purposes.

# The following requests are used by the Demo class.
demo:
    error:
        manager: demo
        request: read
        file:    demo
        name:    bogus.nonexistent
    formError1:
        manager: demo
        request: error
        file:    demo
        name:    error1
    formError2:
        manager: demo
        request: error
        file:    demo
        name:    error2
    formError3:
        manager: demo
        request: error
        file:    demo
        name:    error3
    getCart:
        manager: demo
        request: read
        file:    demo
        name:    shoppingCart
    getFormData:
        manager: demo
        request: read
        file:    demo
        name:    formData
    getFruits:
        manager: demo
        request: read
        file:    demo
        name:    fruits
    getPeople:
        manager: demo
        request: read
        file:    demo
        name:    people
    getPerson:
        manager: demo
        request: read
        file:    demo
        name:    person
    getStudents:
        manager: demo
        request: read
        file:    demo
        name:    students
    noData:
        manager: demo
        request: read
        file:    demo
        name:    empty
    tree:
        manager: demo
        request: read
        file:    demo
        name:    tree.top