# dataManagers.yaml --
#
# This dataset defines the "built-in" data managers for Fiz.  These
# data managers are used primarily for demonstration purposes.

# Used by demos to read datasets from disk files.
demo:
  class:         FileDataManager
  pathTemplate:  @home/WEB-INF/demo

# Used by demos to read information from the "test" database. 
demoSql:
  class:        SqlDataManager
  driverClass:  com.mysql.jdbc.Driver
  serverUrl:    jdbc:mysql://localhost:3306/test
  user:         test
  password:     test