# errors.yaml --
#
# This datasheet contains templates used to generate HTML for error
# messages in various situations.  Each template is expanded in the
# context of an error dataset and the main dataset to produce HTML
# to display in a particular location, such as the bulletin or an
# error message for a form element.

# Used when displaying errors in the bulletin area at the top a page.
bulletin: @message

# Used when a post request fails and identifies a particular form element
# as the culprit.  The HML is displayed next to the form element, typically
# in a row underneath it.
formElement: <span class="error">@message</span>

# Used when a FormSection can't be displayed because of an error
# in its data request.
formSection: >
    <div class="sectionError">Can't display this form: @message</div>

# Used when a FormSection can't be displayed because of an error
# in its data request: the expanded result will be displayed as a
# single row in the table.
tableSection: Can't display this table: @message

# Used when a TemplateSection can't be displayed because of an error
# in its a request.
templateSection: >
    <div class="sectionError">Can't display this section: @message</div>

# Used when there is an uncaught exception or error in the page generation
# code for an HTML request.
uncaughtHtml: |
    <div class="uncaughtException">An internal error (uncaught exception)
    occurred while generating this page{{: @message}}.</div>

# The following value is used in conjunction with uncaughtHtml:  if
# this value is "true", then when an uncaught exception occurs Fiz will
# clear any partially-generated HTML before displaying the error message;
# otherwise the partial page will be retained, with the error message
# displayed at the end (this choice shows estate of page generation when the
# error occurred, but it may cause the error message to appear in the middle
# of a partially rendered HTML construct).
clearOnUncaught: true

# Used when there is an uncaught exception or error in the page generation
# code for an AJAX request.  This template is a text template, not an HTML
# template: it creates a text message that is returned to the browser.
uncaughtAjax: >
    An internal error (uncaught exception) occurred on the server
    while handling an AJAX request: @message.  This page may not
    function correctly without a refresh.
