# main.yaml -
#
# This dataset contains overall configuration options for Fiz.

# The following value is overwritten by Fiz during initialization to
# hold the home directory where all of the files for this application
# reside (the "context root" for the Servlet).
home: TBD

# When attempting to dynamically load a class and the className doesn't
# include a package name, Fiz first tries the name with no package.  If
# that class doesn't exist then Fiz tries prepending each of the package
# names in the following (comma-separated) list:
searchPackages: "org.fiz"

# If the line below is uncommented it means that Fiz is running in
# debug mode.  Debug mode has the following impact:
#   * All of Fiz's internal caches will be cleared at the start of each
#     request.  This is useful so that file modifications become visible
#     immediately without restarting the application.  Of course, it will
#     make Fiz run *much* more slowly, so it shouldn't be used in production
#     or when measuring performance.
# By the way, if there is a FIZ_DEBUG environment variable its value
# overrides any value specified below.
# debug: 1

