# main.yaml -
#
# This dataset contains overall configuration options for Fiz.

# The following value is overwritten by Fiz during initialization to
# hold the home directory where all of the files for this application
# reside (the "context root" for the Servlet).
home: TBD

# When attempting to dynamically load a class and the className doesn't
# include a package name, Fiz first tries the name with no package.  If
# that class doesn't exist then Fiz tries prepending each of the package
# names in the following (comma-separated) list:
searchPackages: "org.fiz"

# If the following value is set to "true" than all of Fiz's internal
# caches will be cleared before each request.  This is useful in debug
# configurations so that file changes take effect immediately without
# restarting the application.
clearCaches: true

